name: demoflu
description: Simplify package demonstration with a versatile web application for showcasing widget usage.
version: 2.0.0
repository: https://github.com/caduandrade/demoflu

screenshots:
  - description: Shows an example of the widget being demonstrated.
    path: screenshots/screenshot_2_v2.png

topics:
  - ui
  - demo
  - widget
  - package

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
  flex_color_picker: ^3.4.1
  syntax_highlight: ^0.4.0
  meta: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true